FROM python:3.13
WORKDIR /app
COPY . .
ARG HTTP_PROXY
ARG HTTPS_PROXY
ENV HTTP_PROXY=http://fg-proxy.corp.tele2.ru:8080
ENV HTTPS_PROXY=http://fg-proxy.corp.tele2.ru:8080
ENV PIP_NO_VERIFY_CERTS=1
ENV PIP_DISABLE_PIP_VERSION_CHECK=1
RUN pip install --no-cache-dir \
    --trusted-host pypi.org \
    --trusted-host files.pythonhosted.org \
    termcolor
CMD ["python", "docker_example.py"]